name: Deploy static site to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: <tên-app-service-của-bạn>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
